version: '3.6'
services:
    postgresql:
        container_name: 'postgresdb'
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - './data/postgres:/var/lib/postgresql/data'
        ports:
            - "5433:5432"
        networks:
            - main_network

    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: project-gitlab
        restart: always
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://192.168.1.163:8088'
                'DB_HOST=${DB_URL}'
                'DB_PORT=${DB_PORT}'
                'DB_USER=gitlab'
                'DB_PASS=${DB_PASSWORD}'
                'DB_NAME=gitlabhq_production'

        ports:
            - '8088:8088'
        volumes:
            - './data/gitlab/config:/etc/gitlab'
            - './data/gitlab/logs:/var/log/gitlab'
            - './data/gitlab/data:/var/opt/gitlab'
        shm_size: '256m'
        depends_on:
            - postgresql
        networks:
            - main_network

    backend:
        container_name: 'java-spring-boot-backend'
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgresql
        ports:
            - '8080:8080'
        networks:
            - main_network
        env_file:
            - .env

networks:
    main_network:
        driver: bridge